version: "3.3"

services:
  node:
    restart: unless-stopped
    container_name: node
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./telegram-chatgpt-bot:/var/www
    command:
      - /bin/sh
      - -c
      - |
        node index.js
